# Build and validate the specification suite using bikeshed
#
# TODO: publish to github pages on release
#
# based on https://w3c.github.io/spec-prod/#examples

name: CI
on:
  push:
    branches:
      - development
      - v2-suite
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - source: index.bs
            destination: index.html
          - source: core/index.bs
            destination: core/index.html
          - source: records/index.bs
            destination: records/index.html
          - source: schemas/index.bs
            destination: schemas/index.html
          - source: bulk/index.bs
            destination: bulk/index.html
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
